---
kind: pipeline
name: orchestrator-tests

steps:
  - name: orchestrator-test
    image: python:3.10
#    environment:
#      FLASK_APP: "app:create_app('config/test-config.yml', False)"
    commands:
#      - pip install --upgrade pip setuptools wheel
#      - pip wheel -r requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
#      - pip wheel -r test-requirements.txt --wheel-dir=wheeldir --find-links=wheeldir     -
#      - pip install --no-index --find-links=wheeldir -r requirements.txt
#      - pip install --no-index --find-links=wheeldir -r test-requirements.txt
      - pip3 install -r requirements.txt --user
      - pip3 install -r test-requirements.txt --user
      - python3 -m pytest --no-header -vv --disable-warnings

services:
  - name: redis
    image: redis:7.0.0
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms2g -Xmx2g