---
version: 2.1

jobs:
  ensure_formatting:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt --user
      - run:
          name: install test-dependencies
          command: pip install -r test-requirements.txt --user
      - run:
          name: confirm black version
          command: black --version
      - run:
          name: run black check
          command: black --check .
  linter:
    docker:
      - image: alpine/flake8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: flake8
          command: flake8 --ignore=E,W ~/repo
  tests:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt --user
      - run:
          name: install test-dependencies
          command: pip install -r test-requirements.txt --user
      - run:
          name: install pytest
          command: pip install pytest pytest-cov --user
      - run:
          name: run pytest
          command: python3 -m pytest --cov=pycti

workflows:
  version: 2
  opencti_client_python:
    jobs:
      - ensure_formatting:
          filters:
            tags:
              only: /.*/    
      - linter:
          filters:
            tags:
              only: /.*/    
      - tests:
          filters:
            tags:
              only: /.*/      
